# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui',
# licensing of 'mainwindow.ui' applies.
#
# Created: Sun Jun 30 12:19:17 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 10, 801, 551))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 351, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lights_on_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.lights_on_button.setObjectName("lights_on_button")
        self.verticalLayout.addWidget(self.lights_on_button)
        self.lights_off_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.lights_off_button.setObjectName("lights_off_button")
        self.verticalLayout.addWidget(self.lights_off_button)
        self.dim_lights_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.dim_lights_button.setObjectName("dim_lights_button")
        self.verticalLayout.addWidget(self.dim_lights_button)
        self.bright_lights_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bright_lights_button.setObjectName("bright_lights_button")
        self.verticalLayout.addWidget(self.bright_lights_button)
        self.set_white_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.set_white_button.setObjectName("set_white_button")
        self.verticalLayout.addWidget(self.set_white_button)
        self.set_red_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.set_red_button.setObjectName("set_red_button")
        self.verticalLayout.addWidget(self.set_red_button)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(379, 10, 401, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.light_list = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.light_list.setObjectName("light_list")
        self.verticalLayout_2.addWidget(self.light_list)
        self.set_light = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.set_light.setObjectName("set_light")
        self.verticalLayout_2.addWidget(self.set_light)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 450, 551, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.r_value = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.r_value.setObjectName("r_value")
        self.horizontalLayout_3.addWidget(self.r_value)
        self.g_value = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.g_value.setObjectName("g_value")
        self.horizontalLayout_3.addWidget(self.g_value)
        self.b_value = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.b_value.setObjectName("b_value")
        self.horizontalLayout_3.addWidget(self.b_value)
        self.rgb_enter = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.rgb_enter.setObjectName("rgb_enter")
        self.horizontalLayout_3.addWidget(self.rgb_enter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.lights_on_button.setText(QtWidgets.QApplication.translate("MainWindow", "Lights On", None, -1))
        self.lights_off_button.setText(QtWidgets.QApplication.translate("MainWindow", "Lights Off", None, -1))
        self.dim_lights_button.setText(QtWidgets.QApplication.translate("MainWindow", "Dim", None, -1))
        self.bright_lights_button.setText(QtWidgets.QApplication.translate("MainWindow", "Bright", None, -1))
        self.set_white_button.setText(QtWidgets.QApplication.translate("MainWindow", "Set to White", None, -1))
        self.set_red_button.setText(QtWidgets.QApplication.translate("MainWindow", "Set to Red", None, -1))
        self.set_light.setText(QtWidgets.QApplication.translate("MainWindow", "Set Light", None, -1))
        self.r_value.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Red", None, -1))
        self.g_value.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Green", None, -1))
        self.b_value.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Blue", None, -1))
        self.rgb_enter.setText(QtWidgets.QApplication.translate("MainWindow", "Set RGB", None, -1))

